[package]
name = "unkdir_api"
version = "0.1.0"
authors = ["garyemerson <gmohammadioun@gmail.com>"]
edition = '2018'

[dependencies]
postgres = { version = "0.19.1", features = ["with-chrono-0_4"] }
chrono = { version = "0.4.6" }
json = "0.12.4"
